version: '3.9'
services:
  db:
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: password
    restart: on-failure
  app:
    build: .
    ports:
      - 80:8080
    links:
      - db
    restart: on-failure
    environment:
      DB_RECONNECT_TIMES: 5
      DB_RECONNECT_BOUNCE_SEC: 1
      SERVER_ADDR: 0.0.0.0:8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
      DB_DRIVER: postgres
