basePath: /api/v1
definitions:
  controller.CreateAccountResponse:
    properties:
      message:
        type: string
    type: object
  controller.HelloWorld:
    properties:
      message:
        type: string
    type: object
  form.AccountSignup:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact:
    email: shengwei199505@gmail.com
    name: API Support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Studygroup
  version: "1.0"
paths:
  /account:
    post:
      consumes:
      - application/json
      description: Create Account
      parameters:
      - description: account info to create
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/form.AccountSignup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CreateAccountResponse'
      summary: Create Account
      tags:
      - Account
  /hello-world/:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.HelloWorld'
      summary: ping example
      tags:
      - hello world
swagger: "2.0"
