basePath: /api/v1
definitions:
  controller.HelloWorld:
    properties:
      message:
        type: string
    type: object
info:
  contact:
    email: shengwei199505@gmail.com
    name: API Support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Studygroup
  version: "1.0"
paths:
  /hello-world/:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.HelloWorld'
      summary: ping example
      tags:
      - example
swagger: "2.0"
